### ISSUE TITLE
selecting 'kong' storage does not work and inconsistent behaviour of cert storage location when using vault as storage when running kong in hybrid mode

### ISSUE THREAD

**Issue by Hydrogenhax** [Kong/kong-plugin-acme#73]
Hello,

I've been testing the acme plugin on my kong hybrid mode setup which consists of 1 control plane and 1 data plane node.
I did not see any section in the documentation specifically pertaining to kong hybrid mode setups so I'll post my issue here and hope it gets picked up or someone can point me in the right direction.

The issue I have encountered is that the plugin does not function when setting storage to `kong`, the `/.well-known/acme-challenge ` is not intercepted, i.e., the path `/.well-known/acme-challenge/x` does not return `Not Found`.
I'm assuming this is due to the nature of hybrid mode, the data plane is technically running in "DB-less" mode, although the control plane does have a Postgres DB.
To check if it is indeed selecting `kong` as the storage that is causing the plugin to not function, I changed the storage to `shm` and the plugin started working as querying the acme-challenge path does return a `Not Found`.

As I would like my certs to persist even with restarts, but the `kong` storage was not working, I chose `vault` for storage and input the relevant configs to connect with my vault instance. This is where I observed some inconsistencies in cert storage location.

If I triggered a cert creation or renewal from the control plane with the provided command 
`curl http://localhost:8001/acme -d host=mydomain.com` the certs and keys actually get stored in the Postgres DB under certificates table, while some other configs for the certs are stored in vault.
If I triggered a cert creation by hitting the domain using `curl https://mydomain.com -k` instead, the certs are stored in vault together with the relevant configs.

This is my first attempt at configuring Kong and the acme plugin and may have missed out some details.
Ideally, I would be able to get the plugin to work with storage as `kong` and leave vault out of the equation entirely as that would be an additional dependency. But if that is not possible due to the nature of hybrid mode then I hope there can be some guidance on how to prevent the inconsistency in cert storage location so that the entire setup can be cleaner.

Thanks in advance!

**Comment by fffonion** [comment]
Hi @Hydrogenhax those are very insightful observations. In currrent hybrid mode, kong storage is not working 
"properly".

If the cert is applied with proxy request (an HTTPS request comes to `https://mydomain.com` that triggers the creation
of cert), those challenge responses would be stored in DP side's acme_storage DAO. Since DP runs in dbless, Kong will complain you can't modify the DAO. Actually even if allows you to do so, it can't work well if you have multiple DP nodes,
as there's no mechanism to sync any changes made on DP back to CP (or to other DPs).
If the cert is applied using admin API, as you mentioned, it will techinically work. Since those challenge responses
are created on CP then propogates to DP. But in hybrid mode there's delayed config sync so it *might* be too early
ACME server start to validate it before DP receives those DAO objects. We can make some improvements in this approach
like wait for a while for example.

This will also be made better when Kong has a solid communication channel between CP and DPs.

Regarding the inconsistency of storage: those non-kong storages are initially made for dbless, where kong nodes doesn't
have other cluster wide communication mechanism. I think we indeed want to follow the consistency here, i will PR for that as well.

**Comment by Hydrogenhax** [comment]
Hi @fffonion,

Appreciate the quick response and detailed explanation on this issue.
Just want to add another observation that those certs applied from admin API from the control plane do not seem to be able to auto-renew, while those applied from proxy request with the certs stored in vault are able to be auto-renewed. Just a heads up for anyone else attempting to use the acme plugin with a hybrid setup.

Thanks again!
